runtime: python37 #set the language etc

# instance_class: F2 #the instance class, determining the application's computing resources.
# #the F2 class gives a memory limit if 512MB, CPU limit of 1.2GHz and automatic scaling types.

# env_variables: #defines enviornmental variables
#   BUCKET_NAME: "example-gcs-bucket" #this variable is not being used in my app, just an example.

# handlers: #lists static files to be served
# # Matches requests to /images/... to files in static/images/...
# #also not being used in my app, just for an example
# - url: /images
#   static_dir: static/images

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto