
steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:18.09.6'
  - '--file=Dockerfile-18.09.6'
  - '.'
images: 'gcr.io/$PROJECT_ID/myimage'