FROM launcher.gcr.io/google/ubuntu16_04

LABEL maintainer="Michal Shaffer <chalshaff12@gmail.com>"

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip nginx
RUN pip3 install uwsgi
RUN python3 -m venv venv
RUN soucre venv/bin/activate
RUN pip3 install -r requirements.txt
RUN python3 app.py

ENTRYPOINT ["/cisc3140python2"]